services:
  # mongodb:
  #   container_name: "mongodb"
  #   image: "mongo:latest"
  #   environment:
  #     - "MONGO_INITDB_DATABASE=mongodb"
  #     - "MONGO_INITDB_ROOT_PASSWORD=mongodb"
  #     - "MONGO_INITDB_ROOT_USERNAME=root"
  #   ports:
  #     - "27017"

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379"
