services:
  mongodb:
    image: "mongo:latest"
    environment:
      - "MONGO_INITDB_DATABASE=mongodb"
      - "MONGO_INITDB_ROOT_PASSWORD=mongodb"
      - "MONGO_INITDB_ROOT_USERNAME=root"
    ports:
      - "27017"
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432"
  redis:
    image: "redis:latest"
    ports:
      - "6379"
