server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  # data:
  #   mongodb:
  #     uri: mongodb://root:mongodb@localhost:27017/mongodb
  #     database: mongodb

  # mail:
  #   host: smtp.mailtrap.io
  #   port: 2525
  #   username: gusdn0828@gmail.com
  #   password: your_password
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

  redis:
    host: localhost
    port: 6379
    reactive:
      url: redis://localhost:6379

jwt:
  secret-key: your_secret_key
