server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10

  data:
    redis:
      host: localhost
      port: 6379
      url: redis://localhost:6379

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            # scope:
            #   - profile
            #   - account_email

        #   mongodb:
#     uri: mongodb://root:mongodb@localhost:27017/mongodb
#     database: mongodb

# mail:
#   host: smtp.mailtrap.io
#   port: 2525
#   username: gusdn0828@gmail.com
#   password: your_password
#   properties:
#     mail:
#       smtp:
#         auth: true
#         starttls:
#           enable: true

jwt:
  secret-key: your_secret_key
