spring:
  config:
    activate:
      on-profile: default
  main:
    web-application-type: reactive

  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        #        - id: users
        #          uri: lb://USERS
        #          predicates:
        #            - Path=/users/**
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: catalogs
          uri: lb://CATALOGS
          predicates:
            - Path=/catalogs/**
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
